name: ci
on:
  push:
    branches:
      - 'data_update'

jobs:
  update-data:
    name: update bank data
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: run update data script
      run: ./data/update-data.sh

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: run test
      run: go test loader/lib_test.go 

    - name: commit updated data
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "updated bank data"


